(let* ((name "{___PYTHON_PLACEHOLDER_BUFFER___}")
       (heading "{___PYTHON_PLACEHOLDER_HEADING___}")
       (content "{___PYTHON_PLACEHOLDER_CONTENT___}")
       (buffer (or (get-buffer name) (generate-new-buffer name)))
       (current-line-empty-p (lambda ()
                               (save-excursion
                                 (beginning-of-line)
                                 (looking-at-p "[[:space:]]*$")))))
  (with-current-buffer buffer
    (unless (eq major-mode 'org-mode)
      (org-mode))
    (goto-char (point-min))
    (when (> (buffer-size) 0)
      (goto-char (point-max)))
    (unless (funcall current-line-empty-p)
      (newline))
    (insert heading)
    (newline)
    (insert "#+begin_src python")
    (newline)
    (insert content)
    (newline)
    (insert "#+end_src")
    (newline)
    (set-window-point (get-buffer-window buffer 'visible)(point-max))))
